### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Loizos099** [ykjit/hwtracer#104]
Hello,

I am getting errors while trying to build the cargo, am new to rust, I did a bit of research and tried compiling again using rustup nightly, which compiled successfully, but the tests fails. Also I managed to build a previous version 5d98a99 with rustup stable, tests run okay but simple_example produces no data. I would appreciate if I can get some help. I want to use hwtracer to do analysis on executed instructions for my thesis.
One more thing, I tried compiling the simple_example.rs while linking the libhwtracer.rlib but compiler still complains that cannot find hwtracer crate, any thoughts on that?

Error building with rustup stable(I tried using std::os::unix::io::AsRawFd which worked but cant seem to fix the  `#![feature]` from which I found out that I have to build using nightly  ):

```
error[E0432]: unresolved import `std::os::fd::AsRawFd`
 --> src/decode/libipt/mod.rs:5:48
  |
5 | use std::{convert::TryFrom, env, ffi::CString, os::fd::AsRawFd, ptr};
  |                                                ^^^^^^^^^^^^^^^ no `AsRawFd` in `os::fd`

error[E0603]: module `fd` is private
 --> src/decode/libipt/mod.rs:5:52
  |
5 | use std::{convert::TryFrom, env, ffi::CString, os::fd::AsRawFd, ptr};
  |                                                    ^^ private module
  |
note: the module `fd` is defined here

error[E0554]: `#![feature]` may not be used on the stable release channel
 --> src/lib.rs:3:12
  |
3 | #![feature(once_cell)]
  |            ^^^^^^^^^

error[E0599]: no method named `as_raw_fd` found for struct `NamedTempFile` in the current scope
  --> src/decode/libipt/mod.rs:86:31
   |
86 |                 vdso_tempfile.as_raw_fd(),
   |                               ^^^^^^^^^ method not found in `NamedTempFile`
   |

```

Stable simple_example run for version 5d98a99 
```
Backend configuration: Dummy
trace1: num_blocks=0, result=1376

trace2: num_blocks=0, result=1186

trace3: num_blocks=0, result=1187
```

**Comment by vext01** [comment]
Hi,

hwtracer will probably only work with nightly Rust.

> , I did a bit of research and tried compiling again using rustup nightly, which compiled successfully, but the tests fails

Can you paste the output?

Does your CPU support Intel PT?

**Comment by vext01** [comment]
[I should also mention that this library is experimental and probably not really ready for consumption by the masses. We freely break the API]

**Comment by Loizos099** [comment]
Hi,

Thank you for the quick response, turns out it was a mistake from my side "of course", there was an error with virtualization thats why I could not get Intel Pt to work. When I set it up properly it should probably work. I will use this for experimental purposes. I was wondering if hwtracer supports printing decoded instructions like ptxed and is it possible with slide modifications on the collect/decode code to attach and decode another process. 

Thank you,

**Comment by vext01** [comment]
> I was wondering if hwtracer supports printing decoded instructions like ptxed

Afraid not.

> is it possible with slide modifications on the collect/decode code to attach and decode another process

Nope. hwtracer caters to a very niche use-case.

Have you considered using the [perf userspace tools for Linux](https://man7.org/linux/man-pages/man1/perf-intel-pt.1.html)? You may have more luck with those as they are general purpose tools.

**Comment by ltratt** [comment]
Oops, phantom mouse click -- sorry!

**Comment by Loizos099** [comment]
Thank you for your help
